---
title: Assignment 1 Instructions
format: html
---
Due Date: 2/18/26 (FLEX to 2/23/26)  
{{< iconify icon-park-outline:preview-open >}}
<a href="#" 
   data-bs-toggle="popover" 
   data-bs-trigger="click" 
   onclick="return false;"
   data-bs-boundary="viewport"
   data-bs-html="true" 
   data-bs-sanitize="false" 
   data-bs-content='<iframe src="https://rmwillia-umbc.github.io/CMSC436/hello.html" width="350" height="250" style="border:none;"></iframe>' 
   title="Resource Preview">
   <span>{{< iconify icon-park-outline:preview-open >}}</span>
</a>


::: {.callout-note collapse="false" title="FLEX rules"}
* you have to get started to FLEX!  
* Aim for the original due date, then message me if you need to FLEX  
* Be aware of accumulating deadlines when you think about FLEXING
:::

# AI use policy for this assignment {#ai-use-policy-for-this-assignment}
Note that AI use is never required. 

::: {.callout-warning}
If you do choose to use AI, please disclose it and include a link to the chat. 
:::

todo

# Assignment Objective {#assignment-objective}

This assignment is designed to simulate a real-world data visualization task where you will analyze, deconstruct, and accurately recreate a provided visualization using a tool of your choice (you can use more if you like). One of the most important skills in the workforce is choosing the right tool for the job—using two different tools in this assignment will help you get a sense for the varying levels of **features, interactivity, and customizability** available with different visualization software tools, how to pick the right one, and which ones you would rather avoid (this will help you when it comes time to pick tools for your group project!). 

::: {.callout-note collapse="false" title="tl;dr"}
Choose one or two visualization(s) from [this collection](https://padlet.com/rmwillia2/vis-o-the-day-4zfmrymkyzvf9vzo). Each visualization is accompanied by the dataset that was used to generate it. Write some code to recreate the visualization(s) as accurately as you can using two different visualization tools from the [list of approved tools](https://padlet.com/rmwillia2/approved-visualization-tools-6rzddfbf6hhfjrdd). You can try two different tools on one vis, or you can try two different tools on two different images–your choice. Document your process, including how you loaded the data, formatted it, and adjusted the parameters available in the tools. Submit the code you wrote to generate the visualizations. Reflect on your choices and challenges in a structured response, comparing the two tools.
:::

# How to Submit {#submitting-your-work}

Submit your work in the following formats:

* **Final Visualizations \+ captions** (.pdf, .docx, or .ppt). Put the captions below the image (or use the built-in captioning functionality of the tool, if applicable)  
* **Process Documentation** (Notebook File, PDF, Word, or .mp4) and **Code Files** (include any files necessary to run the code)  
* **Reflection Response** (Complete via Blackboard, which links to Google Assignments. Don’t forget to press submit\!)

::: {.callout-warning}
**Please do not put it in a zip archive!**
:::

<a href="#ti-example" 
   class="btn btn-link p-0" 
   data-bs-toggle="collapse" 
   data-bs-target="#ti-example .callout-collapse" 
   onclick="setTimeout(() => { document.getElementById('ti-example').scrollIntoView({behavior: 'smooth'}); }, 100)">
   scrollWhat if I want/need to use a different format?
</a>

# Assignment Instructions: Step-by-Step {#assignment-instructions:-step-by-step}

## Step 0: Choose one or two Visualizations to Recreate {#step-0:-choose-one-or-two-visualizations-to-recreate}

1. Browse the set of [provided visualization images and datasets](https://padlet.com/rmwillia2/assignment-1-visualizations-data-4zfmrymkyzvf9vzo). Each vis is accompanied by the dataset used to create it.  
2. Select one or two visualizations to attempt to recreate.  
3. Familiarize yourself with the dataset and its structure. Do some exploring on the [Data to Viz](https://www.data-to-viz.com/) site to learn common vis names, caveats, and some tips to create them. As a hint, I have put the chart name in brackets for each image (though sometimes names will differ\!)  
4. Decide whether you will use AI or not – if you use it, be sure to include the link in your submission


## Step 1: Recreate Visualization \#1 with your chosen tool {#step-1:-recreate-visualization-#1-with-your-chosen-tool}

1. Choose an appropriate tool from the [list of approved tools](https://padlet.com/rmwillia2/approved-visualization-tools-6rzddfbf6hhfjrdd), based on the dataset and visualization type. You can change your mind at any time.  
2. Load and prepare the dataset.  
   * The dataset may require preprocessing (e.g., filtering, cleaning, or restructuring) to match the visual representation in the original image. You should document any changes you make to the dataset to recreate the visualization. You can add auxiliary data as needed, but don’t forget to cite and document it\! \[[Do we have to write code to stream the data from the Google Docs link, or can we download it locally and then read it in?](#bookmark=id.8yvkszgw1t77)\]  
3. Write some code to recreate the visualization(s) as accurately as you can using two different visualization tools from the [list of approved tools](https://padlet.com/rmwillia2/approved-visualization-tools-6rzddfbf6hhfjrdd).  
   * \[[Do I need to try and replicate even the little icons and shapes?](#bookmark=id.burplpmbxhqr)\]  
   * \[[Do we have to match the colors too?](#bookmark=id.h25ax63jqgvt)\]  
   * \[[What if I can’t get an exact 1:1 replica?](#bookmark=id.mfu7lmakmw3)\]  
4. As part of your submission, provide a step-by-step breakdown of how you created each visualization (any data cleaning or transformation required, how to change the formatting to match the original, how to add text and/or annotations). Your documentation should be clear enough that another student could **follow your steps and recreate your visualization** without prior knowledge of the tool. \[[How beautiful does my code need to be?](#bookmark=id.lbe8ciwzqk0q)\]. You can do this by choosing one or more of these options:  
   * Interspersing markdown cells with your code cells in notebook environments, such as [Colab](https://colab.google/), [Jupyter](https://jupyter.org/), [Observable](https://observablehq.com/), [R](https://rmarkdown.rstudio.com/lesson-10.html), [Matlab](https://www.mathworks.com/products/matlab-online.html) (preferred option). Also export to .pdf if possible.  
   * Use [Quarto](https://quarto.org/) to intersperse text and code (node you’ll still need to upload the runnable code)  
   * Including block comments in your code, and line comments as well (ok option, but gets hard to read fast)  
   * Screenshotting code snippets and putting them into a word doc interspersed with text (not recommended, but you do you)  
   * Narrating a screen-capture video of you writing the code while explaining what you’re doing. Be sure to include closed captions/subtitles (great choice if you don’t like fiddling with documents) \[[Can I use AI to generate the narration?](#bookmark=id.hxrrrt1zcsi)\]








Where should I put the resources? on this page? or on a "next" in navigation?

Also, should group the assignments into a top-navigation item, then link in the corresponding week overview (right that's one of the things i hate about BB)

# Frequently Asked Questions {#sec-faqs}

::: {#ti-example .callout-tip .faq-callout icon=false appearance="default" collapse="true" title="What if I want/need to use a different format?"}


Add an ID starting with `#tip-` to reference a tip.
:::

::: {#tip-example2 .callout-tip .faq-callout  icon=false appearance="default" collapse="true"}
## Cross-Referencing a Tip

Add an ID starting with `#tip-` to reference a tip.
:::
::: {#tip-example3 .callout-tip .faq-callout   icon=false appearance="default" collapse="true"}
## Cross-Referencing a Tip

Add an ID starting with `#tip-` to reference a tip.
:::

See @sec-faqs


<a href="https://rmwillia-umbc.github.io/CMSC436/hello.html" 
   data-bs-toggle="popover" 
   data-bs-trigger="hover" 
   data-bs-html="true" 
   data-bs-sanitize="false" 
   data-bs-content='<iframe src="https://rmwillia-umbc.github.io/CMSC436/hello.html" width="300" height="200" style="border:none;"></iframe>' 
   title="">
   Hover to see Example.com
</a>

<iframe style="border: 0; width: 100%; height: 450px;" allowfullscreen frameborder="0" src="https://raindrop.io/amjussayinisall/cmsc-436-approved-tools-66316166/embed/theme=dark"></iframe>

<script>
document.addEventListener("DOMContentLoaded", function() {
  var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
  var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
    return new bootstrap.Popover(popoverTriggerEl, {
      sanitize: false, // Prevents Bootstrap from deleting your iframe
      html: true       // Allows the iframe to render as a tag
    })
  })
});
</script>


