---
title: Week 1 Overview
format: html
---

Info for Week 1
<iframe width="560" height="315" src="https://www.youtube.com/embed/-S8a70KXZlI?si=t88jZPgBa4JUGJQn" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

or 

{{< video https://www.youtube.com/embed/-S8a70KXZlI?si=t88jZPgBa4JUGJQn >}}



{{< video https://ethics.org.au/deontology/ >}}

<p><iframe width="560" height="315" src="https://docs.google.com/document/d/1OONb7Gg7OQAeOp86GXWXhecvR62M2kIl3eQsJBv8XWg/preview?pli=1"></iframe></p>

::: {#assignment-1}
<p><iframe width="100%" height="800" src="https://docs.google.com/document/d/1fqvFFV5XeH3AiVmMkwijXvOiO78G-ASnnm16e_2jPmw/preview?pli=1"></iframe></p>

caption
:::

# Chapter 2.2: Deontology

Burton, Emanuelle; Goldsmith, Judy; Mattei, Nicholas; Siler, Cory; Swiatek, Sara-Jo. Computing and Technology Ethics: Engaging through Science Fiction. MIT Press. Kindle Edition.   
**Approximate reading time: 45-55 minutes (Word count \~6100)**  
**Sections** 

[2.2 DEONTOLOGY](#2.2 deontology)

[2.2.1 OVERVIEW OF DEONTOLOGY](#2.2.1 overview-of-deontology)

[2.2.2 DEONTIC FORMS OF AUTHORITY AND TRADITIONS](#2.2.2 deontic-forms-of-authority-and-traditions)

[Political Authority](#political-authority)

[Divine Authority](#divine-authority)

[The Authority of Human Reason](#the-authority-of-human-reason)

[2.2.3 KANTIAN DEONTOLOGY](#2.2.3 kantian-deontology)

[2.2.4 PRINCIPLES IN PRACTICE](#2.2.4 principles-in-practice)

[2.2.5 MODALITIES FOR JUDGMENT](#2.2.5 modalities-for-judgment)

[How Fundamental Is It?](#how-fundamental-is-it?)

[How Relevant Is It?](#how-relevant-is-it?)

[Sidebar: Prioritizing the Right over the Good](#sidebar:-prioritizing-the-right-over-the-good)

[2.2.6 STRENGTHS AND WEAKNESSES OF DEONTOLOGY: IT’S NOT ALL ABOUT RULES](#2.2.6 strengths-and-weaknesses-of-deontology:-it’s-not-all-about-rules)

[Sidebar: The Challenges of Deontology and Artificial Intelligence](#sidebar:-the-challenges-of-deontology-and-artificial-intelligence)

# 2.2 DEONTOLOGY  {#2.2 deontology}

Deontology as an approach to ethics is best characterized by its focus on duties, rights, and moral obligations. Its two main presuppositions are that ethical evaluation primarily concerns the rightness or wrongness of actions and that ethical reasoning should help determine what we ought to do.

## 2.2.1 OVERVIEW OF DEONTOLOGY {#2.2.1 overview-of-deontology}

The word “deontology” comes from the Greek word deon, meaning duty, obligation, or “that which is binding,” and \-ology, indicating a particular branch of knowledge. Deontology has existed in various forms. One of the most famous is associated with the 18th-century German philosopher Immanuel Kant. Kant’s moral philosophy has been so influential that people sometimes refer to “Kantianism” as though it is its own ethical theory, similar to—although distinct from—deontology. Below we discuss Kantianism as an important development of an older tradition in which moral principles are said to be obtainable through human reason.   
Despite its many variations, deontology does have some defining characteristics. Most notably, deontology emphasizes the rightness or wrongness of an action by reference to certain action-guiding principles. Depending on the context, these principles can be described as laws, rules, maxims, imperatives, or commands. Whatever the terms used, these principles are said to place certain constraints on human action. These constraints apply—or at the very least must be seriously considered—even in situations in which the consequences of an action are understood to be desirable or good.   
Because deontology bears a minor resemblance to the simplistic, black-and-white thinking that many people associate with ethics, this complex and nuanced framework is frequently misunderstood in three specific ways. The first misunderstanding is that deontology is simple: you figure out what the law is, and then you do what it tells you to do or avoid doing what it does not permit you to do. For many people, this is what ethics is all about: adhering to basic rules and laws. But the demands of duty are complex, and balancing those many demands requires careful reflection, not just blind adherence.   
The second misunderstanding is that because it is difficult to honor one’s many duties at the same time, you can therefore pick and choose which laws to follow as a matter of individual choice or preference (or perhaps a matter of avoiding the least desirable punishments). But simply acting on preferences and regarding those preferences as if they are binding laws is not an accurate description of deontology. In fact, this kind of picking and choosing has more in common with moral relativism than it does with any of the ethical frameworks that we discuss in this chapter. A moral relativist is someone who believes that all moral judgments are based on individual viewpoints and that no one viewpoint ought to be privileged above any other—save that person’s own, because most moral relativists are critical of anyone who disagrees with their position on the matter (Midgley 1991).   
The third misunderstanding is that because deontology considers intention to be important, it therefore does not consider consequences to be important at all. The problem with this description of deontology is that it presents only a partial picture. It may help us understand the points of emphasis within a deontological framework, but it is a characterization that obscures deontology’s many specificities and variations. Most forms of deontology acknowledge the ethical significance of the consequences and context of moral actions and choices (Rawls 1999, especially p. 26), even though they emphasize principles, laws, rules, and obligations that guide human action and decision making. Where these duties and moral obligations come from, and how they relate to each other, depend on the form or style of the deontology in question.   
Unlike the simplistic and piecemeal approaches described above, deontology offers an approach to ethics that is morally practicable without abandoning the seriousness of moral laws. Deontology presumes that moral obligations are a real part of human life and cannot be dispensed with because they are inconvenient, even while it recognizes that honoring all of one’s moral obligations is rarely a straightforward task. For a deontologist, the task of ethics is not to choose which obligations to follow but rather to consider all one’s moral obligations in order to determine how to live and to act in light of all of them, especially in situations that put (or seem to put) these obligations in tension with one another.  
Although deontology requires us to take account of all of the rules, laws, and duties that bind us, this does not mean that deontologists consider every single rule, law, or duty to be equally binding. For instance, both jaywalking and manslaughter are against the law in the United States, but very few people would be willing to argue that these two laws are equally meaningful or significant. However, most of the time the distinctions are more subtle, and even in situations in which people have acknowledged that a particular code of laws has legitimacy, it is not always easy to figure out what those laws and duties require of us at any given moment. Deontology does not demand that we follow the law regardless of circumstances—that wouldn’t make any sense, because nothing in our lives ever happens apart from specific circumstances. Rather, the task of deontology is to understand how best to honor one’s duties within those circumstances.   
The laws proscribed and enforced by the government are one kind of rule, but of course they are not the only kind. Some rules or duties may be particular to a community, such as religious dietary laws, and others may apply only to a subgroup within a community, such as doctors’ obligation to provide medical care in moments of need. (For more on profession-specific obligations—specifically those for programmers and technology developers—see chapter 6.) Different communities may have different ideas about which parts of human life must be guided by these rules and which parts are free of moral obligation.  
It should come as no surprise that much of our lives is governed by rules, laws, and principles of actions. Many human actions and behaviors are explainable as following rules or laws, often without giving them much thought, such as walking on sidewalks instead of in the street or going to the end of the line at your favorite hot dog stand. There are also various rules of etiquette that we acknowledge, follow, and sometimes knowingly break, though for most deontologists these more day-to-day kinds of rules are not necessarily morally significant. Although it is easy to presuppose that rules and laws are burdens, especially in cultures in which freedom is highly valued, these less-significant rules make many aspects of our shared lives easier to negotiate and harmonize. Rules can even provide satisfactions of their own: after all, rules are what makes it possible to play many kinds of games and sports together.   
A law, rule or duty will matter only if it is rooted in an authority that is recognized as legitimate. Not all deontologists recognize the same authorities, or even the same kinds of authority. Often, deontologists will specifically reject a law they take to be illegitimate—such as a state law that prohibits carrying weapons or criminalizes political protest—precisely because another system or authority they take to be more legitimate points them in a different direction. Also, deontologists can share a commitment to a particular law or duty, such as respecting the property of others or a prohibition against murder, but have different explanations for what makes that duty authoritative. 

## 2.2.2 DEONTIC FORMS OF AUTHORITY AND TRADITIONS  {#2.2.2 deontic-forms-of-authority-and-traditions}

In order to highlight the variation within deontology as a framework for thinking about ethics, below we introduce three different traditions that are deontological in their orientation. Each of them appeals to a particular kind of authority to justify and legitimate moral obligations and duties. The first tradition appeals to a “social contract,” and therefore the authority of the law is grounded in a political claim about what it means to live together in a society under reasonable principles that can be applied to all. The next tradition grounds the authority of moral obligations and constraints on the existence of a god or gods, to whom duty is owed and who determine human beings’ duties to others. Finally, we consider a tradition of deontology that insists that the basic principles of morality are to be derived from human reason. The feature that unifies all three of these traditions and warrants, describing them as deontological, is not a particular authority, duty, or even rule-governed action but is rather the belief that there is a difference between right and wrong and that this difference is supported by an authoritative claim about how we ought to act toward others and, in some cases, toward ourselves.   
It is important to note that these traditions are not mutually exclusive. Thus, there is nothing preventing a deontologist from arguing that moral obligations can be grounded by all three forms of authority discussed in the following sections. These traditions were selected because in many ways they are defined by which authority they deem most important with regard to morally binding principles and norms. 

### Political Authority  {#political-authority}

Political authority comes from an organized human society. There are many forms of political authority, which vary with political systems. Authority is distinct from power, which in this context means the ability to materially enforce rules and punishment, irrespective of legitimacy. Most political systems and leaders claim to operate from a position of legitimate authority, serving the interests of the people, even if in practice they operate from a position of power.   
An example of a deontological tradition grounded in political authority is contractarianism. Contractarianism begins from the presupposition that human beings are primarily, if not solely, driven by self-interest, and therefore the best strategy for deciding which institutions, principles, and social rules can legitimately place constraints on our otherwise selfish actions is first to find the ones on which all would agree. Hence, the need for a contract. In other words, ethical principles and norms require us to sometimes act in ways that we would prefer not to act but are justified on the grounds that it is better to cooperate than to be constantly at odds with each other. Agreement among individuals has normative importance. Contractarianism grew out of an older tradition known as social contract theory, which dates to Thomas Hobbes in the early seventeenth century (Cudd and Eftekhari 2018). Hobbes insisted that humans are driven solely by their own self-interest but because they are too fragile and weak to live on their own, it is necessary to be part of a society in which individuals sacrifice some of their freedom and agree to be governed by a sovereign authority in which disputes and self-interest can be mitigated appropriately (Hobbes \[1668\] 1992). Although starting from the same basic premise—that human beings are primarily driven by their own self-interest— contractarianism, as it has been more recently formulated, focuses less on the giving up of rights and powers to a government authority and more on what “reasonable” people would decide and execute judgment under democratic rule. 

### Divine Authority  {#divine-authority}

Divine authority is authority from God or gods. If a set of laws is understood to have been given or revealed by a divine figure, then those laws gain their legitimacy from the existence and power of that God or gods. Different religious traditions have different ideas about how humans gain knowledge of these laws. In some traditions, these laws are said to be contained in holy books or sacred writings. In other cases, divine law is considered to be received through prophecy or through authoritative leaders. The ethical weight of an action might also be interpreted as gaining its authority from a God or gods without necessarily using the language of law.   
Divine command theory is one form of deontology that derives its authority from God. Broadly speaking, divine command theory holds that moral obligations consist of obedience to God. Under divine command theory, an action is obligatory because God or the gods command it and it is impermissible if God or gods forbid it. If that action is neither obligatory nor forbidden, it is considered to be a permissible action (Quinn 2006).  
Although the notion of god-given laws is conceptually straightforward, there is an interesting philosophical problem at their core: did god(s) give this law because it is right, or is the law right because it comes from god(s)? This is sometimes referred to as the Euthyphro problem, referring to a dialogue written by Plato in which Socrates asks, “Is the pious loved by the gods because it is pious, or is it pious because it is loved by the gods? ” (Plato, Euthyphro 10a1–3). Most divine command traditions do not have a settled answer to this question, and it is a topic of ongoing philosophical and religious debate.

### The Authority of Human Reason  {#the-authority-of-human-reason}

The notion that human beings have an inherent moral compass that allows them to discern the difference between right and wrong is an ancient idea that became especially popular during the European intellectual movement known as the Enlightenment (more on this below). Over the centuries, theologians and philosophers have linked this belief in the human’s inherent capacity to judge between right and wrong to religious dispositions and creation stories. In the book of Genesis, for example, the first humans are said to know the difference between right and wrong. Thomas Aquinas, a Christian philosopher and theologian, argued that the very first principle of practical reasoning (i.e., ethical reflection on human action) is quite simple: avoid evil and do the good (Aquinas Summa Theologica I–II, 94, 2; see Aquinas 1948). Aquinas insisted that all human beings know this basic principle and therefore can discern the difference between right and wrong. While Aquinas appealed to a divine authority to support this claim, he also linked this capacity to the human’s ability to grasp the laws that govern and order the universe (i.e., natural laws).   
Natural law theory as a tradition has also been articulated in less religious and metaphysical terms. As one theorist explains:

*Natural law theory accepts that law can be considered and spoken of both as a sheer social fact of power and practice, and as a set of reasons for action that can be and often are sound as reasons and therefore normative for reasonable people addressed by them. This dual character of positive law is presupposed by the well-known slogan “Unjust laws are not laws.” (Finnis 2020\)* 

Natural law theorists do not hold that ethics is simply a matter of sensing the difference between right and wrong, nor do they claim that deciding what to do in particular situations is easy. In fact, most natural law theorists are careful to point out that acting morally is very difficult and that it requires a certain amount of sacrifice. Even more, they tend to emphasize that even in those cases in which we know what the right choice is, we often fail to act in ways that are right and just. For someone with the outlook of Aquinas, this shows that natural reason needs to be supplemented and guided by religious texts and teaching. For secular theorists, this means that discerning what is right and wrong is never a private enterprise but must be worked out in a social context in which people deliberate about the ends that are worth pursuing. 

## 2.2.3 KANTIAN DEONTOLOGY {#2.2.3 kantian-deontology}

The notion that the universe is ordered by laws that can be apprehended by human reason was an especially popular belief in the eighteenth century, when Immanuel Kant was developing his philosophy. Kant’s moral philosophy is similar to Aquinas’s in that Kant believed that human beings are able to discern the difference between right and wrong. However, Kant was also writing at a time when people were becoming increasingly critical of claims that depended on religious authority, whether in the context of politics, of science, or of morality. And therefore Kant, as many other enlightenment thinkers, rejected the idea that any code of law handed down in a religious tradition or promulgated by the state can successfully address the full breadth and complexity of right and wrong.   
Kant acknowledged that external laws often aligned with the moral law in basic ways and that many (or even most) people require such externally given laws to remind them of their fundamental duties to others. He also believed that external laws can be valuable both as constraints on our behavior and as guidelines for our moral understanding. However, Kant insisted that human reason is the most important guide to making moral choices. Because Kant remains one of the most influential figures in moral philosophy and because he is frequently described as a deontologist, it is worth explaining his approach to ethics in a little more detail.   
Kant’s version of deontology is uniquely universalist in scope. It starts from the assumption that all human beings are free and rational and that they are familiar with both the experience of being moved by desire and the experience of being moved by the feeling of duty or moral obligation. In response to this baseline assumption, Kant offers an account of what must necessarily be true in order for us to make sense of this universal experience of moral duty. He understood himself to be offering a “metaphysics of morals,” in which he aimed to articulate the universal pattern of reasoning behind a moral judgment (Kant 1996).   
According to Kant, the unity and intelligibility of the moral law is something all rational beings can grasp. The moral law therefore must be perfect, and perfectly consistent, in a manner similar to the order of nature. This means in practice that whereas all our particular duties to individuals, coworkers, family, and friends are important, they are conditional and therefore cannot describe the basic sense of duty that applies in every circumstance. For Kant, only those actions that are unconditional have moral value. So what kind of actions are these?   
For Kant, an action performed in accordance with a law or set of laws does not necessarily mean that action has moral worth. Kant strongly believed that people should learn to think for themselves and never blindly follow any one law or set of laws. And even when following an external law is in order, that does not necessarily endow it with moral worth. In order for an action to have moral worth, it must be an action that you, the agent, recognize as right. But just as importantly, it must be binding for all rational agents. Otherwise it would be, again, conditional. Only actions that meet both of these criteria have moral worth. According to Kant, our capacity to act on such a law is the only indication that we are truly free agents. Contrary to popular opinion, freedom is not about acting on whatever desires and impulses one might have in a particular moment, nor is it following a rule to avoid punishment or condemnation. True freedom, Kant maintained, is the freedom to act according to a law that you can both apply to yourself and universally legislate for all. A law such as this is what Kant calls a categorical imperative, by which he means a law that is unconditionally and universally valid. His first formulation of this law is as follows: 

*Act only in accordance with that maxim through which you can at the same time will that it become a universal law. (Kant 1996, 73\)* 

Let’s consider what this means in more general terms. Kant’s understanding of morality requires us to evaluate an action using criteria identified by internal reasoning processes, rather than criteria drawn from outside legal codes and cultural norms. Before acting, a moral agent must always ask herself: “If I act in such a way, is this something I can legislate for myself and all other rational agents? Is it something I can continue to follow and expect others to do the same? ” Lying is a classic example of an action that might seem justifiable in a particular instance but cannot be justified as a general practice. If you tell a lie, can you honestly and consistently legislate that action? Can you coherently argue that it makes sense, morally speaking, for everyone to be able to lie whenever it is convenient for them? If not, then clearly lying is unethical, and therefore, a person shouldn’t lie under any circumstances.   
Kant’s categorical imperative, as he formulates it initially, is intentionally abstract. It is meant to capture something very basic about the experience of moral obligation. But he also offers a formulation that speaks more to how we are to treat others. His second formulation of the categorical imperative reads: 

*Act that you use humanity, whether in your own person or in the person of any other, always at the same time as an end, never merely as a means. (Kant 1996, 80\)* 

This second formulation of the categorical imperative is derived from an additional claim that because the human being is a rational creature and therefore are capable of acting freely, all human beings should be treated with respect and dignity. Whenever we treat another person merely as a means to achieve some particular end, we are not only disrespecting that person: we are disrespecting all humanity, including ourselves. 

## 2.2.4 PRINCIPLES IN PRACTICE {#2.2.4 principles-in-practice}

It might seem at first that all deontologists—or at least those who acknowledge the same authority behind moral principles or laws—would agree with one another about what the right action is in any given situation. But in practice, those who approach ethics from within a deontological framework—yes, even Kantians—disagree all the time. Although they may share the same general idea about the status of “the law” as the source of ethics and the only guide to ethical action, disagreement often arises around the meaning of that particular law and/or how it should be applied. Furthermore, most people recognize more than one system of law, even if they think that one (or more) of those systems is more important or that one system or code of law is limited in some way. This introduces a difficult question: what is the right way to resolve an issue when different laws seem to prescribe conflicting solutions? When a person is duty-bound by more than one set of laws—for example, religious laws and laws of the state—how do they decide how to navigate conflicts between them or decide when one should take precedence over the other? What kinds of punishments are warranted by different kinds of violations? These are difficult questions to answer, but rather than providing decisive answers, most deontological traditions instead offer additional guidelines, suggestions, and even rules about how to proceed when conflicts and tensions arise. 

## 2.2.5 MODALITIES FOR JUDGMENT {#2.2.5 modalities-for-judgment}

It is rarely possible to satisfy every single duty, or to satisfy them equally well, because circumstances often create tensions between our various duties. This is largely because regardless of their authority, deontology grounds its rules and laws in relationships. When our duties to different people pull us in different directions, or when a given duty relationship is multidimensional (such as a parent’s relationship to their child or a person’s relationship to their spouse), it is sometimes impossible to honor every duty, or every dimension of one’s duty. When these conflicts of duty arise—as they inevitably do—a moral agent is forced to make judgments about which duties should be prioritized over the others. For deontologists, these priority judgments cannot simply be a matter of personal preference—after all, the whole point of a duty is that it’s binding, even when it’s inconvenient or unpleasant.   
When balancing competing duties, a deontologist must consider the following two concerns. 

### How Fundamental Is It?  {#how-fundamental-is-it?}

Which duty is most fundamental? Of the many duties competing for your attention and action, which ones are the most important to who you are and your role in the world? In a situation that compels a person to choose between protecting a stranger and protecting their child, nearly every deontologist would argue that it’s right and appropriate to protect the child, not because the agent has no duties at all to the stranger but because parents have particular duties toward their children.  
But this determination might be more complicated if the agent is an expert or professional (such as a doctor or a firefighter) who is trained to respond to the crisis at hand, because many such experts and professionals believe that their expertise imposes a specific obligation to use their skills and training to help others when possible, or have even signed onto a professional code that requires them to do so. Even if that parent still protects their child instead of the stranger, they may feel more keenly that they have failed in their duty to the other person.

### How Relevant Is It?  {#how-relevant-is-it?}

Which duty is most relevant to the situation in question? When you are making a decision about a specific situation, it is often the case that some of your many duties are more pressing than others because of the particular circumstances. Imagine a soldier in a combat situation whose platoon-mate is injured in pursuit of the enemy. Should this soldier stop and assist her injured comrade, or complete the mission and kill the enemy? Both of these duties are important, but which is more relevant? The answer will depend on a number of very specific factors: how badly injured is her comrade? Is anyone else available to help him? How likely is it that there will be another chance to kill this enemy?  
It is worth remembering that for a civilian who is not bound to fight the enemy (and might even carry a strong prohibition against killing other people), this tension would be very different. Both soldier and civilian have a duty to help another person who is injured and in need, but the soldier has other duties that the civilian does not, and those duties might be more relevant than helping the wounded.   
These two criteria enable a deontologist to balance the basic obligations that shape their life (the fundamental) against the particular demands of specific circumstances (the relevant). When a deontologist deprioritizes a specific duty—for example, if the soldier above drops her pursuit of the enemy to assist her platoon-mate—that person is neither rejecting nor ignoring that one duty; rather, they are determining that the best way to honor the full range of their duties requires them to prioritize other duties over that one in this particular moment.

| Sidebar: Prioritizing the Right over the Good |
| :---- |
| Unlike some other approaches to ethics, it is frequently said that deontology is not organized around the question of what is good, but rather it is primarily concerned with what is “right.” A system organized around “right” may initially seem more constricting than a system organized around goodness, because right/wrong is a binary system and goodness is not. But deontology actually allows for more freedom than goodness-based systems. A system concerned with goodness can encompass anything: any person, deed, or object can be evaluated in terms of how good it is compared to other things. When goodness is the metric for ethics, it’s (almost) always possible to get better, and being good requires that one constantly try to become better. A system of right and wrong, by contrast, leaves room for actions and experiences that are outside the bounds of ethical evaluation—that is, they are neither right nor wrong, and people can pursue those actions or not purely according to their preferences. |

## 2.2.6 STRENGTHS AND WEAKNESSES OF DEONTOLOGY: IT’S NOT ALL ABOUT RULES  {#2.2.6 strengths-and-weaknesses-of-deontology:-it’s-not-all-about-rules}

One of deontology’s strengths is that it insists upon the notion that there is a difference between the rightness and wrongness of action, and it does so by appealing to factors that do not automatically depend on the way the outcome of that action is received. In this way, deontology preserves the integrity of ethical action: our choices have value, regardless of whether other people recognize that value. At its worst, deontological thinking can enable fanaticism, leading people to believe they are justified in punishing others for doing things they take to be wrong. At its best, deontology can afford people the moral courage to stand against the majority, even when there is no obvious reward for doing so.   
Another common criticism of deontology is that it does not focus enough on the consequences of action. Although it is true that deontology prioritizes human actions and intentions, as suggested above, most forms of deontology not only address but seriously consider the consequences and context of decisions and actions. Yet because of its emphasis on principles (laws, rules, and codes), deontology on its own seems to capture only a small portion of what it means to do ethics. And even more than that, it seems to operate as though the ethical life is a judicious process backed by a particular type of authority. In the mid-twentieth century, Elizabeth Anscombe offered a powerful argument against the legalistic language that was then dominant in moral discourse, arguing that without religious backing, such language makes very little sense and that therefore, unless we want to impose its religious significance upon everyone who wants to weigh in on matters of ethics, we ought to abandon it altogether. In her words:

*The concepts of obligation and duty—moral obligation and moral duty, that is to say—and of what is morally right and wrong, and of the moral sense of “ought,” ought to be jettisoned if this is psychologically possible; because they are survivals, or derivatives from survivals, from an earlier conception of ethics which no longer generally survives, and are only harmful without it. (Anscombe 1958, 1\)* 

Those forms of deontology that claim to ground the authority of moral principles and norms in human reason rather than divine decree have also been criticized. Kantian deontology in particular is frequently criticized for being overly rigorous and impractical. As noted, Kant insists that an action has no moral worth if it is not done out of duty. This means that, for instance, when someone donates to a charity and finds that the act brings them joy, and they decide to donate again and again, according to Kantian standards, this action has no moral worth. It is for reasons like this that people sometimes call Kant a moral purist or rigorist (Cohen 2014). Kant claims that a truly moral act is motivated by respect for the moral law and free from any other particular inclinations or desires. But human experience tells us that most of us act for a variety of reasons, and desire and emotion cannot easily be cast aside in order to evaluate the moral worth of particular actions—whether our own or someone else’s.   
But perhaps the most important issue that arises within a deontological framework concerns what to do when conflicting duties arise. Although we have described some of the ways deontology handles conflicts and inconsistencies, the fact remains that the principles and rules that guide human conduct are not always easy to follow nor are the choices between them always clear. Quite often, the complexity of our lives and circumstances makes it impossible to abide by all of the rules and duties that bind us, no matter what we do. The impossibility of choosing a perfect course does not mean that deontology has failed or that those rules or duties cease to be binding. Instead, these clashes of duty should be seen as the reason deontology is valuable: it furnishes us with a way of thinking, perceiving, and living that enables us to realistically navigate difficult choices about the things that matter most. That said, there are other ethical frameworks to consider and other points of emphasis to consider as well.

| Sidebar: The Challenges of Deontology and Artificial Intelligence |
| :---- |
| For most deontologists, the right or wrong decision must always be a choice; otherwise, one cannot take responsibility for it. The agent may feel a strong sense of obligation, or the call to duty might be strong, but in order for responsibility to exist there must be a choice, and the agent must have the capacity to choose differently. Defining deontology becomes complicated when we start thinking about automated agents, which are programmed to do certain tasks and which learn new things according to programs that have been written by humans. Are automated entities exercising responsibility in the deontological sense? Could this be on the horizon?  Deontology focuses on duties and obligations. What kinds of entities have duties and obligations? Typically, when we reference duties, rights, and obligations, we have in mind other people. But what are our duties with respect to other living creatures? And what about future generations? These are the types of questions deontology has traditionally asked. But new issues arise when we consider human beings’ relation to intelligent machines. What does a robot owe to a human? What does a human owe to a robot? What kind of demand can an artificial being make on human life, and how would that demand be justified? What these questions point to is a certain ambiguity about the nature of the relationship between humans and intelligent machines. If robots cannot have relationships with others, then what is at stake when we delegate a moral decision to a robot?  There is a growing body of work in computer science and related fields called machine ethics (i.e., programming or teaching machines how to act ethically) (Christian 2020; Dubber et al. 2020; Lin et al. 2017; Pereira and Lopes 2020; Wallach and Asaro 2020). Work in this area typically takes one of two main forms. In the bottom-up approach, systems or agents are given examples of proper behavior and attempt to abstract from those what to do in particular situations. In the top-down approach, systems or agents are given a set of rules in some formal, logical language and are expected to incorporate these rules into the actions that they decide to take. An important stream of research in this area focuses on harnessing the creativity of complex machine learning methods while still enforcing that the agents make decisions in line with outside constraints or rules (Rossi and Mattei 2019). There has been a lot of press coverage of work in this area related to teaching autonomous cars how to act by surveying millions of people all over the world (Bonnefon et al. 2016). One key question for us is, do machines even have ethics? Whereas they can have rules or patterns of behavior, who or what is held responsible for the decisions they make?  Consider self-driving cars. They are trained by being given “traces” of human drivers as well as a set of rules to follow. They observe human drivers obeying traffic laws, avoiding obstacles, stopping for errant pedestrians, and other actions. If an autonomous vehicle stops for a pedestrian, a moose, or a flock of ducklings in the road, can it be said to be acting ethically? Note that moose are large, and that hitting one can do significant damage to a vehicle and possibly the occupants of the vehicle as well as to the moose. Does it make it less ethical (or less of an ethical concern) to stop for a moose than for a smaller animal? Does the vehicle’s decision to stop for the ducklings come from a respect for life or from a societal consensus to not injure cute animals? |

